# Nixpacks Plan for Railway
[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["cd backend && npm install"]

[start]
cmd = "node backend/server.js"
